name: umi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - bwa
  - cutadapt
  - filtlong
  - gawk
  - medaka
  - minimap2
  - parallel
  - porechop
  - racon
  - samtools
  - seqtk
  - vsearch
