on: ['push']

jobs:
  nanopore_pipeline:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    steps:
      - uses: actions/checkout@v2
      - run: |
          ln -s longread_umi.sh longread_umi
          echo "::add-path::${PWD}"
          . /opt/conda/etc/profile.d/conda.sh
          conda env create -n umi -f environment.yaml
          conda activate umi
      - working-directory: test_data
        run: |
          longread_umi nanopore_pipeline -d test_reads.fq -o . -v 30 -w rrna_operon -t 1 -q r941_min_high_g303
  qc_pipline:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    steps:
      - uses: actions/checkout@v2
      - run: |
          ln -s longread_umi.sh longread_umi
          echo "::add-path::${PWD}"
          . /opt/conda/etc/profile.d/conda.sh
          conda env create -n umi -f environment.yaml
          conda activate umi
      - working-directory: test_data
        run: |
          longread_umi qc_pipeline -d test_reads.fq -c consensus_raconx3_medakax1.fa -r zymo_curated -t 1
